In [2]:
# from urllib.request import urlretrieve

# urlretrieve('https://d17h27t6h515a5.cloudfront.net/topher/2016/October/580a829f_train/train.p', 'train.p')
# urlretrieve('https://d17h27t6h515a5.cloudfront.net/topher/2016/October/580d880c_bvlc-alexnet/bvlc-alexnet.npy', 
#             'bvlc-alexnet.npy')

('bvlc-alexnet.npy', <http.client.HTTPMessage at 0x2b79c98bc88>)

In [1]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6]])

In [2]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
x = np.array([[ 0,  1,  2], [ 3,  4,  5], [ 6,  7,  8], [ 9, 10, 11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
rows = np.array([0, 3])
columns = np.array([0, 2])
print(x[rows, columns])

[ 0 11]


In [6]:
np.ix_(rows, columns)

(array([[0],
        [3]]), array([[0, 2]]))